### ISSUE TITLE
Building runc 1.1.11 causes 

### ISSUE THREAD

**Issue by jpalermo** [opencontainers/runc#4169]
### Description

We import several packages from runc into a library we maintain and after updating the package to 1.1.11 we started getting the following errors when running `go build`
```
/var/vcap/data/packages/golang-1-linux/4c9041a93ce507bdc9572a0325ac35774020ee9c/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/bin/ld: /var/vcap/data/tmp/go-link-3302366506/000024.o: in function `_cgo_2cacdc9ff070_Cfunc_spawn_userns_cat':
/tmp/go-build/cgo-gcc-prolog:68: undefined reference to `spawn_userns_cat'
collect2: error: ld returned 1 exit status
```

We were able to resolve the problem by exporting `CGO_ENABLED=0`.

I'm only opening the issue in case somebody else runs into the same problem. I'll be closing it immediately.

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

n/a

### What version of runc are you using?

1.1.11
