### PR TITLE
libcontainer: fix compilation on GOARCH=arm GOARM=6 (32 bits)

### LINKED ISSUE #1818: Build fails with GOOS=linux GOARCH=386 due to int overflow
In fresh golang environments (in docker container):
```
$ docker run --rm -it golang bash
root@0b225ff49f25:/go# go get github.com/opencontainers/runc
root@0b225ff49f25:/go# go version
go version go1.10.3 linux/amd64

(snip)

root@0b225ff49f25:/go/src/github.com/opencontainers/runc# make BUILDTAGS="" GOARCH=386
go build -buildmode=pie  -ldflags "-X main.gitCommit="dd56ece8236d6d9e5bed4ea0c31fe53c7b873ff4" -X main.version=1.0.0-rc5+dev " -tags "" -o runc .
go build github.com/opencontainers/runc/libcontainer/nsenter: build constraints exclude all Go files in /go/src/github.com/opencontainers/runc/libcontainer/nsenter
# github.com/opencontainers/runc/libcontainer/system
libcontainer/system/linux.go:119:89: constant 4294967295 overflows int
Makefile:32: recipe for target 'runc' failed
```

It looks like this is caused by #1688. `IDMap.Count` is defined as int, and in 32bit environment 4294967295 is too large for int.

(In fact I don't use runc directly, but uses opencontainers/runc/libcontainer from other libraries.)

### PR DESCRIPTION
**Pull request by tiborvass**
This fixes the following compilation error on 32bit ARM:
```
$ GOARCH=arm GOARCH=6 go build ./libcontainer/system/
libcontainer/system/linux.go:119:89: constant 4294967295 overflows int
```

Signed-off-by: Tibor Vass <tibor@docker.com>

Related to #1688
Fixes #1818

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
> seccomp_test.go:365: time="2018-06-14T18:07:54Z" level=fatal msg="panic from initialization: parseLine only accepts {*string, *int, *[]string} as arguments! (*int64)(0xc420013500) is not a pointer!, goroutine 1 [running, locked to thread]:

I think we can just add `*int64` to https://github.com/opencontainers/runc/blob/0e561642f81e84ebd0b3afd6ec510c75a2ccb71b/libcontainer/user/user.go#L113

**Comment by cyphar** [comment]
LGTM.

**Comment by mrunalp** [comment]
LGTM

**Comment by tiborvass** [comment]
Thank you very much!
