### ISSUE TITLE
build fails with musl libc

### ISSUE THREAD

**Issue by ncopa** [opencontainers/runc#761]
When building with musl libc build fails with this error:

````console
go build -ldflags "-X main.gitCommit=9384f484ff795fb049f1dd2dc977536baae472c3" -tags "seccomp" -o runc .
# github.com/opencontainers/runc/libcontainer/nsenter
Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c:21:27: fatal error: bits/sockaddr.h: No such file or directory
compilation terminated.
Makefile:16: recipe for target 'all' failed
make: *** [all] Error 2
````

According the glibc source, the `bits/sockaddr.h` header should [never be included directly](https://github.molgen.mpg.de/git-mirror/glibc/blob/20003c49884422da7ffbc459cdeee768a6fee07b/bits/sockaddr.h#L20), instead `sys/socket.h` should be used instead.

**Comment by ncopa** [comment]
This was introduced with 3c2e77eed56a571265631694f898c29142c32da3 (Fri Jan 29, Add a compatibility header for CentOS/RHEL 6)

**Comment by jfrazelle** [comment]
that was probably added when docker was still supported on rhel6 i say remove, but ianam

**Comment by ncopa** [comment]
It was added in jan 2016.

I'm testing a fix in centos 6. PR coming up soon...

**Comment by jfrazelle** [comment]
whoa... someone crazy enough to run in rhel 6 😱

On Tue, Apr 19, 2016 at 12:57 AM, Natanael Copa <notifications@github.com>
wrote:

> It was added in jan 2016.
>
> I'm testing a fix in centos 6. PR coming up soon...
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencontainers/runc/issues/761#issuecomment-211782818>
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by ncopa** [comment]
apparently someone does.

I am a bit confused. runc does not build in centos6 container:
````console
[root@daccdb27cd88 runc]# make
go build -ldflags "-X main.gitCommit=8e129e097220b2591edd59957c4ff08e064e14b9" -tags "seccomp" -o runc .
go: GOPATH entry is relative; must be absolute path: "".
Run 'go help gopath' for usage.
make: *** [all] Error 2
[root@daccdb27cd88 runc]# GOPATH="$PWD" make
go build -ldflags "-X main.gitCommit=8e129e097220b2591edd59957c4ff08e064e14b9" -tags "seccomp" -o runc .
# github.com/seccomp/libseccomp-golang
Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go:298: invalid operation: in.toNative() == *_Cvar_C_ARCH_BAD (mismatched types C.uint32_t and C.uint)
Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go:328: invalid case *_Cvar_C_ARCH_X86 in switch on a (mismatched types C.uint and C.uint32_t)
Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go:330: invalid case *_Cvar_C_ARCH_X86_64 in switch on a (mismatched types C.uint and C.uint32_t)
Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go:332: invalid case *_Cvar_C_ARCH_X32 in switch on a (mismatched types C.uint and C.uint32_t)
Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go:334: invalid case *_Cvar_C_ARCH_ARM in switch on a (mismatched types C.uint and C.uint32_t)
Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go:336: invalid case *_Cvar_C_ARCH_NATIVE in switch on a (mismatched types C.uint and C.uint32_t)
Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go:338: invalid case *_Cvar_C_ARCH_AARCH64 in switch on a (mismatched types C.uint and C.uint32_t)
Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go:340: invalid case *_Cvar_C_ARCH_MIPS in switch on a (mismatched types C.uint and C.uint32_t)
Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go:342: invalid case *_Cvar_C_ARCH_MIPS64 in switch on a (mismatched types C.uint and C.uint32_t)
Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go:344: invalid case *_Cvar_C_ARCH_MIPS64N32 in switch on a (mismatched types C.uint and C.uint32_t)
Godeps/_workspace/src/github.com/seccomp/libseccomp-golang/seccomp_internal.go:344: too many errors
make: *** [all] Error 2
[root@daccdb27cd88 runc]# 
````

however, the file in question does build just fine without the `bits/sockaddr.h` include:
````console
[root@daccdb27cd88 runc]# git diff
diff --git a/libcontainer/nsenter/nsexec.c b/libcontainer/nsenter/nsexec.c
index 8f37d6c..40a8f89 100644
--- a/libcontainer/nsenter/nsexec.c
+++ b/libcontainer/nsenter/nsexec.c
@@ -18,7 +18,6 @@
 #include <unistd.h>
 #include <grp.h>
 
-#include <bits/sockaddr.h>
 #include <linux/types.h>
 
 // All arguments should be above the stack because it grows down
[root@daccdb27cd88 runc]# gcc -Wall -c libcontainer/nsenter/nsexec.c 
[root@daccdb27cd88 runc]# 
````

So i wonder why exactly was this line added in first place?

**Comment by ncopa** [comment]
It was added due to this error (which happens when building the commit before, 7d423cb7a11ac85427dfe740f2b7cddbfbb68f95)
````
In file included from Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c:20:
/usr/include/linux/netlink.h:35: error: expected specifier-qualifier-list before 'sa_family_t'
make: *** [all] Error 2
````

However, the `#include <bits/sockaddr.h>` is no longer needed after commit 
394fb55d85b9a40c3193eca85588ea2e06cf9081, which fixes the same problem, but in a correct way.

The line can safely be removed.

**Comment by cyphar** [comment]
@ncopa Would you mind making a PR for it?
